"""Analyzer-layer package built on top of wendao-core-lib."""

from ._version import __version__
from .config import AnalyzerConfig, AnalyzerStrategy
from .models import (
    AnalysisSummary,
    AnalyzerResultRow,
    QueryAnalysisRun,
    RepoAnalysisRun,
    RowsAnalysisRun,
    TableAnalysisRun,
    parse_analyzer_result_rows,
)
from .runtime import (
    analyze_query,
    analyze_query_results,
    analyze_repo_query_text,
    analyze_repo_query_text_results,
    analyze_repo_search,
    analyze_repo_search_results,
    analyze_result_rows,
    analyze_rows,
    analyze_table,
    analyze_table_results,
    run_query_analysis,
    run_repo_analysis,
    run_repo_search_analysis,
    run_rows_analysis,
    run_table_analysis,
    summarize_query,
    summarize_query_results,
    summarize_query_route,
    summarize_repo_analysis,
    summarize_repo_search,
    summarize_repo_search_results,
    summarize_repo_query_text,
    summarize_repo_query_text_results,
    summarize_rows,
    summarize_rows_analysis,
    summarize_table,
    summarize_table_analysis,
    summarize_result_rows,
)
from .strategies import ScoreRankAnalyzer, build_analyzer

__all__ = [
    "__version__",
    "AnalysisSummary",
    "AnalyzerConfig",
    "AnalyzerResultRow",
    "QueryAnalysisRun",
    "RepoAnalysisRun",
    "RowsAnalysisRun",
    "TableAnalysisRun",
    "AnalyzerStrategy",
    "ScoreRankAnalyzer",
    "analyze_query",
    "analyze_query_results",
    "analyze_repo_query_text",
    "analyze_repo_query_text_results",
    "analyze_repo_search",
    "analyze_repo_search_results",
    "analyze_result_rows",
    "analyze_rows",
    "analyze_table",
    "analyze_table_results",
    "run_query_analysis",
    "build_analyzer",
    "parse_analyzer_result_rows",
    "run_repo_analysis",
    "run_repo_search_analysis",
    "run_rows_analysis",
    "run_table_analysis",
    "summarize_query",
    "summarize_query_results",
    "summarize_query_route",
    "summarize_repo_analysis",
    "summarize_repo_search",
    "summarize_repo_search_results",
    "summarize_repo_query_text",
    "summarize_repo_query_text_results",
    "summarize_rows",
    "summarize_rows_analysis",
    "summarize_table",
    "summarize_table_analysis",
    "summarize_result_rows",
]
