from __future__ import annotations

import xiuxian_foundation as foundation


def test_foundation_root_no_longer_exports_helper_facades() -> None:
    for name in (
        "skill_asset",
        "skill_script",
        "skill_reference",
        "skill_data",
        "render_string",
        "SearchResult",
        "EmbeddingClient",
        "get_embedding_client",
        "close_embedding_client",
        "get_embedding_service",
        "EmbeddingService",
        "embed_text",
        "embed_batch",
        "get_dimension",
        "get_rag_adapter",
        "create_rag_adapter",
        "OmniRAGAdapter",
        "DocumentParser",
        "parse_document",
        "parse_documents_batch",
        "RAGConfig",
        "get_rag_config",
        "get_parser",
        "is_knowledge_graph_enabled",
        "is_multimodal_enabled",
        "Chunk",
        "SemanticChunker",
        "SentenceChunker",
        "ParagraphChunker",
        "SlidingWindowChunker",
        "create_chunker",
        "chunk_text",
        "Entity",
        "Relation",
        "EntityMention",
        "ExtractedChunk",
        "EntityType",
        "RelationType",
        "KnowledgeGraphExtractor",
        "get_graph_extractor",
        "extract_pdf_images",
        "get_checkpointer",
        "save_workflow_state",
        "load_workflow_state",
        "get_workflow_history",
        "delete_workflow_state",
        "save_workflow_state_sqlite",
        "load_workflow_state_sqlite",
    ):
        assert not hasattr(foundation, name)
