use std::env;
use std::fs;
use std::io;
use std::path::{Path, PathBuf};

use crate::performance::types::PerfReport;

/// Stable schema ID for JSON reports generated by `xiuxian-testing`.
pub const PERF_REPORT_SCHEMA_VERSION: &str = "xiuxian-testing.perf-report.v1";

fn sanitize_segment(raw: &str, fallback: &str) -> String {
    let trimmed = raw.trim();
    if trimmed.is_empty() {
        return fallback.to_string();
    }

    let mut out = String::with_capacity(trimmed.len());
    for ch in trimmed.chars() {
        if ch.is_ascii_alphanumeric() || ch == '-' || ch == '_' || ch == '.' {
            out.push(ch);
        } else if ch == '/' || ch == '\\' {
            out.push('_');
        }
    }
    if out.is_empty() {
        fallback.to_string()
    } else {
        out
    }
}

fn resolve_runtime_dir(raw_runtime_dir: &str) -> PathBuf {
    let runtime_dir = Path::new(raw_runtime_dir);
    if runtime_dir.is_absolute() {
        return runtime_dir.to_path_buf();
    }

    if let Ok(project_root) = env::var("PRJ_ROOT") {
        return Path::new(&project_root).join(runtime_dir);
    }

    match env::current_dir() {
        Ok(current_dir) => current_dir.join(runtime_dir),
        Err(_) => PathBuf::from(raw_runtime_dir),
    }
}

/// Resolve default report root directory.
#[must_use]
pub fn default_reports_root() -> PathBuf {
    let runtime_dir = env::var("PRJ_RUNTIME_DIR").unwrap_or_else(|_| ".run".to_string());
    resolve_runtime_dir(&runtime_dir).join("reports")
}

/// Build report output path from suite/case/timestamp.
#[must_use]
pub fn report_output_path(suite: &str, case: &str, captured_at_unix_ms: u64) -> PathBuf {
    let mut root = default_reports_root();

    let mut had_segment = false;
    for segment in suite.split('/') {
        let segment = segment.trim();
        if segment.is_empty() {
            continue;
        }
        had_segment = true;
        root.push(sanitize_segment(segment, "suite"));
    }
    if !had_segment {
        root.push("default");
    }

    let file_name = format!(
        "{}-{}.json",
        sanitize_segment(case, "case"),
        captured_at_unix_ms
    );
    root.join(file_name)
}

/// Persist a report to JSON under `.run/reports/...`.
pub fn persist_report(report: &mut PerfReport) -> io::Result<PathBuf> {
    let output_path = report_output_path(&report.suite, &report.case, report.captured_at_unix_ms);
    if let Some(parent) = output_path.parent() {
        fs::create_dir_all(parent)?;
    }

    let payload = serde_json::to_vec_pretty(report)
        .map_err(|error| io::Error::other(format!("serialize report: {error}")))?;
    fs::write(&output_path, payload)?;

    report.report_path = Some(output_path.display().to_string());
    Ok(output_path)
}
